---
{{- range .Values.localQueues }}
---
{{ include "kueue.local-queue" . }}
{{- end }}
{{- range .Values.namespaces }}
{{- if .includeUnreserved }}
{{- $queue := dict "name" "unreserved" "namespace" .name "clusterQueue" "unreserved" }}
---
{{ include "kueue.local-queue" $queue }}
{{- end }}
{{- end }}
{{- range $username := concat $.Values.userNamespaces.users $.Values.userNamespaces.htpasswdUsers }}
{{- range $localQueue := $.Values.userNamespaces.localQueues }}
{{- $userQueue := dict }}
{{- $_ := set $userQueue "name" $localQueue.name }}
{{- $_ := set $userQueue "namespace" (printf "user-%s" $username) }}
{{- $_ := set $userQueue "clusterQueue" $localQueue.clusterQueue }}
---
{{ include "kueue.local-queue" $userQueue }}
{{- end }}
{{- end }}
{{- range $i := until (int $.Values.tenantCount) }}
{{- $n := add1 $i }}
{{- $tName := printf "%s%d" $.Values.tenantPrefix $n }}
{{- range $uname := $.Values.tenantUsers }}
{{- $fullUser := printf "%s-%s" $tName $uname }}
{{- range $lq := $.Values.tenantLocalQueues }}
{{- $cq := "" }}
{{- if $lq.clusterQueueSuffix }}
{{- $cq = printf "%s%s" $tName $lq.clusterQueueSuffix }}
{{- else }}
{{- $cq = $lq.clusterQueue }}
{{- end }}
{{- $userQueue := dict "name" $lq.name "namespace" $fullUser "clusterQueue" $cq }}
---
{{ include "kueue.local-queue" $userQueue }}
{{- end }}
{{- end }}
{{- end }}
