---
{{- range $name, $spec := .Values.resourceFlavors }}
{{- if or (not $.Values.dynamicGpuConfig) (not $spec) (not (hasKey ($spec | default dict) "tolerations")) }}
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
{{- if $spec }}
spec:
  {{- with $spec.nodeLabels }}
  nodeLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $spec.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $spec.topologyName }}
  topologyName: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
