---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.plugin.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.plugin.name }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ .Values.plugin.name }}-cert
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.plugin.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.plugin.name }}
