---
{{- $allUsers := list }}
{{- range .Values.userNamespaces.users }}
{{- $allUsers = append $allUsers . }}
{{- end }}
{{- range .Values.userNamespaces.htpasswdUsers }}
{{- $allUsers = append $allUsers . }}
{{- end }}
{{- range .Values.tenantGroups }}
{{- range .users }}
{{- $allUsers = append $allUsers . }}
{{- end }}
{{- range .htpasswdUsers }}
{{- $allUsers = append $allUsers . }}
{{- end }}
{{- end }}
{{- $allUsers = $allUsers | uniq }}
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: users
users:
{{- range $allUsers }}
  - {{ . }}
{{- end }}
