---
resources:
  - namespace.yaml
  - operatorgroup.yaml
  - label-nodes-job.yaml
  - dashboard/

helmGlobals:
  chartHome: charts

helmCharts:
  - name: fake-gpu-operator
    includeCRDs: true
    releaseName: fake-gpu-operator
    namespace: gpu-operator
    valuesFile: values.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /metadata/namespace
        value: gpu-operator
  - target:
      kind: DaemonSet
    patch: |-
      - op: add
        path: /metadata/namespace
        value: gpu-operator
  - target:
      kind: Service
    patch: |-
      - op: add
        path: /metadata/namespace
        value: gpu-operator
  - target:
      kind: ServiceAccount
    patch: |-
      - op: add
        path: /metadata/namespace
        value: gpu-operator
  - target:
      kind: ConfigMap
    patch: |-
      - op: add
        path: /metadata/namespace
        value: gpu-operator
  - target:
      kind: Role
    patch: |-
      - op: add
        path: /metadata/namespace
        value: gpu-operator
  - target:
      kind: RoleBinding
    patch: |-
      - op: add
        path: /metadata/namespace
        value: gpu-operator
