---
image:
  tag: tenant

gpuDiscovery:
  enabled: false

kueue:
  tenants: "tenanta:tenanta-user-,tenantb:tenantb-user-,tenantc:tenantc-user-"

gpuConfig:
  resources:
    - name: "GB200 Full GPU"
      type: "nvidia.com/gpu"
      count: 8
      share: 0.0625
      gpuEquivalent: 1.0
  totalCpu: 316
  totalMemory: 3460
